examples: Add usage of base64encode
nutanix-cloud-native/packer-plugin-nutanix pull request #131
Opened 2023-07-14 13:49 UTC by mjtrangoni

**What this PR does / why we need it**:
Showcase the usage of **base64encode** for the *user_data* field.
I was looking at using it like on Terraform-side and it works without any issue. 

**How Has This Been Tested?**:
I've run this setup on my Nutanix cluster, and it worked as expected.

**Special notes for your reviewer**:
* No code change, just extend the current examples. Also the *user_data* content is exactly the same.
* Removed some non-needed spaces on `example/source.nutanix.pkr.hcl`.
* Added the default disabled variable, `image_export` as false, so that someone else get to know it quicker. IMHO, this is the purpose of the examples.
* CLA already sent.

**Release note**:
NONE

2023-07-17 09:02 UTC, tuxtof requested changes

2023-07-17 09:02 UTC, tuxtof commented on example/source.nutanix.pkr.hcl
>    user_data         = "I2Nsb3VkLWNvbmZpZwp1c2VyczoKICAtIG5hbWU6IGNlbnRvcwogICAgc3VkbzogWydBTEw9KEFMTCkgTk9QQVNTV0Q6QUxMJ10KY2hwYXNzd2Q6CiAgbGlzdDogfAogICAgY2VudG9zOnBhY2tlcgogIGV4cGlyZTogRmFsc2UKc3No
can you also update this one

2023-07-17 09:10 UTC, mjtrangoni commented on example/source.nutanix.pkr.hcl
>    user_data         = "I2Nsb3VkLWNvbmZpZwp1c2VyczoKICAtIG5hbWU6IGNlbnRvcwogICAgc3VkbzogWydBTEw9KEFMTCkgTk9QQVNTV0Q6QUxMJ10KY2hwYXNzd2Q6CiAgbGlzdDogfAogICAgY2VudG9zOnBhY2tlcgogIGV4cGlyZTogRmFsc2UKc3No
Done

2023-07-17 12:09 UTC, tuxtof approved these changes

2023-07-17 12:22 UTC, merged

2023-07-17 12:23 UTC, tuxtof commented
thanks for your contribution Mario @mjtrangoni

2023-08-02 07:30 UTC, tuxtof commented
HI @mjtrangoni FYI #134

2023-08-02 07:33 UTC, mjtrangoni commented
Interesting. I had no issues with this. Is it something related to one OS?

2023-08-02 07:45 UTC, tuxtof commented
no your example can't work this is pretty strange

a `base64encode("scripts/cloud-init/cloud-config-centos.yaml")` just return  `c2NyaXB0cy9jbG91ZC1pbml0L2Nsb3VkLWNvbmZpZy1jZW50b3MueWFtbA==`

who is the base64 version of the file path and you get the file. path in the user_data file